### ISSUE TITLE
docker-compose failure

### ISSUE THREAD

**Issue by IanSietro** [Netflix/conductor#1725]
Any docker-compose fails with an exception.

### Reproduction steps

    node v10.21.0
    npm 6.14.4
    Docker version 19.03.8
    docker-compose version 1.25.5
    (Docker Restart and pruning of containers/images before the build)

- git clone git@github.com:Netflix/conductor.git
- cd conductor/docker

- **docker-compose up**
```shell
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'conductor'.
> Could not resolve all artifacts for configuration ':classpath'.
> Could not resolve com.mycila.maven-license-plugin:maven-license-plugin:1.10.b1.
    Required by:
        project : > nebula.netflixoss:nebula.netflixoss.gradle.plugin:5.1.1 > com.netflix.nebula:gradle-netflixoss-project-plugin:5.1.1 > gradle.plugin.nl.javadude.gradle.plugins:license-gradle-plugin:0.13.1
    > Could not resolve com.mycila.maven-license-plugin:maven-license-plugin:1.10.b1.
        > Could not parse POM https://jcenter.bintray.com/com/mycila/maven-license-plugin/maven-license-plugin/1.10.b1/maven-license-plugin-1.10.b1.pom
            > Could not resolve com.mycila:parent-pom:5.
            > Could not resolve com.mycila:parent-pom:5.
                > Could not get resource 'https://jcenter.bintray.com/com/mycila/parent-pom/5/parent-pom-5.pom'.
                    > Could not GET 'https://jcenter.bintray.com/com/mycila/parent-pom/5/parent-pom-5.pom'. Received status code 504 from server: Gateway Time-out
```

- **docker-compose up**  (after successful `./gradlew build`)
```shell
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':conductor-grpc-server'.
> Could not resolve all artifacts for configuration ':conductor-grpc-server:classpath'.
   > Could not resolve org.ow2.asm:asm-tree:5.0.3.
     Required by:
         project :conductor-grpc-server > com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:1.2.3 > com.github.jengelman.gradle.plugins:shadow:1.2.3 > org.ow2.asm:asm-commons:5.0.3
      > Could not resolve org.ow2.asm:asm-tree:5.0.3.
         > Could not get resource 'https://plugins.gradle.org/m2/org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.pom'.
            > Could not GET 'https://plugins.gradle.org/m2/org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.pom'. Received status code 504 from server: Gateway Time-out
   > Could not resolve org.apache.ant:ant-launcher:1.9.4.
     Required by:
         project :conductor-grpc-server > com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:1.2.3 > com.github.jengelman.gradle.plugins:shadow:1.2.3 > org.apache.ant:ant:1.9.4
      > Skipped due to earlier error
```

- **docker-compose up —build**
```shell
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'conductor'.
> Could not resolve all artifacts for configuration ':classpath'.
> Could not resolve org.apache.httpcomponents:httpmime:4.3.
    Required by:
        project : > com.github.kt3k.coveralls:com.github.kt3k.coveralls.gradle.plugin:2.8.2 > org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.8.2
    > Could not resolve org.apache.httpcomponents:httpmime:4.3.
        > Could not parse POM https://jcenter.bintray.com/org/apache/httpcomponents/httpmime/4.3/httpmime-4.3.pom
            > Could not resolve org.apache.httpcomponents:httpcomponents-client:4.3.
            > Could not resolve org.apache.httpcomponents:httpcomponents-client:4.3.
                > Could not parse POM https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-client/4.3/httpcomponents-client-4.3.pom
                    > Could not resolve org.apache.httpcomponents:project:7.
                        > Could not resolve org.apache.httpcomponents:project:7.
                        > Could not parse POM https://jcenter.bintray.com/org/apache/httpcomponents/project/7/project-7.pom
                            > Could not resolve org.apache:apache:13.
                                > Could not resolve org.apache:apache:13.
                                    > Could not get resource 'https://jcenter.bintray.com/org/apache/apache/13/apache-13.pom'.
                                    > Could not GET 'https://jcenter.bintray.com/org/apache/apache/13/apache-13.pom'. Received status code 504 from server: Gateway Time-out
> Could not resolve org.ajoberstar:grgit:1.9.3.
    Required by:
        project : > nebula.netflixoss:nebula.netflixoss.gradle.plugin:5.1.1 > com.netflix.nebula:gradle-netflixoss-project-plugin:5.1.1 > com.netflix.nebula:nebula-release-plugin:6.3.5 > org.ajoberstar:gradle-git:1.7.2
    > Skipped due to earlier error
    > Could not resolve org.ajoberstar:grgit:1.9.3.
        > Could not get resource 'https://plugins.gradle.org/m2/org/ajoberstar/grgit/1.9.3/grgit-1.9.3.pom'.
            > Could not GET 'https://plugins.gradle.org/m2/org/ajoberstar/grgit/1.9.3/grgit-1.9.3.pom'. Received status code 504 from server: Gateway Time-out
> Could not resolve com.github.zafarkhaja:java-semver:0.9.0.
    Required by:
        project : > nebula.netflixoss:nebula.netflixoss.gradle.plugin:5.1.1 > com.netflix.nebula:gradle-netflixoss-project-plugin:5.1.1 > com.netflix.nebula:nebula-release-plugin:6.3.5 > org.ajoberstar:gradle-git:1.7.2
    > Skipped due to earlier error
    > Could not resolve com.github.zafarkhaja:java-semver:0.9.0.
        > Could not parse POM https://plugins.gradle.org/m2/com/github/zafarkhaja/java-semver/0.9.0/java-semver-0.9.0.pom
            > Could not resolve org.sonatype.oss:oss-parent:9.
            > Skipped due to earlier error
            > Could not resolve org.sonatype.oss:oss-parent:9.
                > Could not get resource 'https://plugins.gradle.org/m2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom'.
                    > Could not GET 'https://plugins.gradle.org/m2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom'. Received status code 504 from server: Gateway Time-out
```

**Comment by kishorebanala** [comment]
@IanSietro I see this in logs: 

> Could not GET 'https://jcenter.bintray.com/com/mycila/parent-pom/5/parent-pom-5.pom'. Received status code 504 from server: Gateway Time-out

Can you please verify if you're in an unrestricted network, and that you can access these files, say from your browser, without any issues.

**Comment by IanSietro** [comment]
@kishorebanala thank you for the response,
I can access the files, but I cannot verify the cause - my network changed since.

### Update:

`cd docker; docker-compose up` now does not break, yet it still doesn't seem to work properly:

- - -
http://localhost:5000/ → Workflow Defs:

<img width="1378" alt="Screenshot_2020-06-09_at_09_55_52" src="https://user-images.githubusercontent.com/31187902/84101161-95b7df00-aa37-11ea-9779-3b1218c30185.png">

_After changing URL to http://localhost:5000/#/workflow and refreshing the page:_
<img width="1440" alt="Screenshot 2020-06-09 at 10 02 58" src="https://user-images.githubusercontent.com/31187902/84102025-8afe4980-aa39-11ea-9e87-dd94b48e97c8.png">

- - -

Nothing runs on http://localhost:8080/ (expected Swagger).

- - -

Suspicious `cd docker; docker-compose up` logs:

```shell
conductor-server_1  | 0    [main] INFO  com.netflix.conductor.bootstrap.ModulesProvider  - Starting conductor server using dynomite/redis cluster.
conductor-server_1  | 8    [main] WARN  com.netflix.conductor.bootstrap.ModulesProvider  - Starting locking module using Noop Lock.
conductor-server_1  | 282  [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: HTTP
conductor-server_1  | 283  [main] INFO  com.netflix.conductor.contribs.http.HttpTask  - HttpTask initialized...
conductor-server_1  | 286  [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: KAFKA_PUBLISH
conductor-server_1  | 286  [main] INFO  com.netflix.conductor.contribs.kafka.KafkaPublishTask  - KafkaTask initialized...
conductor-server_1  | 288  [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: JSON_JQ_TRANSFORM
conductor-server_1  | Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/client/Client
conductor-server_1  |   at com.netflix.conductor.elasticsearch.ElasticSearchModule.configure(ElasticSearchModule.java:28)
conductor-server_1  |   at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
conductor-server_1  |   at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
conductor-server_1  |   at com.google.inject.spi.Elements.getElements(Elements.java:110)
conductor-server_1  |   at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)
conductor-server_1  |   at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
conductor-server_1  |   at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
conductor-server_1  |   at com.google.inject.spi.Elements.getElements(Elements.java:110)
conductor-server_1  |   at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
conductor-server_1  |   at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
conductor-server_1  |   at com.google.inject.Guice.createInjector(Guice.java:99)
conductor-server_1  |   at com.google.inject.Guice.createInjector(Guice.java:73)
conductor-server_1  |   at com.netflix.conductor.bootstrap.Main.main(Main.java:45)
conductor-server_1  | Caused by: java.lang.ClassNotFoundException: org.elasticsearch.client.Client
conductor-server_1  |   at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
conductor-server_1  |   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
conductor-server_1  |   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
conductor-server_1  |   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
conductor-server_1  |   ... 13 more
conductor-ui_1      | {"name":"Conductor UI","hostname":"4438a0fae212","pid":7,"level":30,"msg":"Serving static /app/ui/dist","time":"2020-06-09T03:14:51.250Z","src":{"file":"/app/ui/dist/webpack:/src/server.js","line":29,"func":"Main.routesConfig"},"v":0}
conductor-ui_1      | {"name":"Conductor UI","hostname":"4438a0fae212","pid":7,"level":30,"msg":"Workflow UI listening at http://0.0.0.0:5000","time":"2020-06-09T03:14:51.347Z","src":{"file":"/app/ui/dist/webpack:/src/server.js","line":44},"v":0}
docker_conductor-server_1 exited with code 1
```

_After opening http://localhost:5000/ → Workflow Defs:_
```shell
conductor-ui_1      | Error: getaddrinfo ENOTFOUND conductor-server conductor-server:8080
conductor-ui_1      |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
conductor-ui_1      | Error: getaddrinfo ENOTFOUND conductor-server conductor-server:8080
conductor-ui_1      |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
```

<img width="1165" alt="Screenshot 2020-06-09 at 09 47 23" src="https://user-images.githubusercontent.com/31187902/84102451-b3d30e80-aa3a-11ea-9937-ad52d7e9a5c8.png">

**Comment by apanicker-nflx** [comment]
Should be fixed in #1733

**Comment by IanSietro** [comment]
@apanicker-nflx please note that the issue was resolved only partially. docker-compose still "fails", please see the previous comment: https://github.com/Netflix/conductor/issues/1725#issuecomment-641004069

---

Swagger not running on http://localhost:8080/

---

http://localhost:5000/ -> Workflow Defs throws an error:
<img width="1440" alt="Screenshot_2020-06-30_at_20_50_28" src="https://user-images.githubusercontent.com/31187902/86134247-96620380-bb13-11ea-9198-d83fc749bcab.png">

**Comment by apanicker-nflx** [comment]
The suspicious logs mentioned above seem to be from an older version which has since been fixed. Please try to run against the latest version.

**Comment by imcyee** [comment]
I had the exact same error, but changing CONFIG_PROP=config-local.properties 
temporary fix the issue. Not sure what causing it.
`
  environment:
      # - CONFIG_PROP=config.properties
      - CONFIG_PROP=config-local.properties # using memory
`

**Comment by ruchitadamodar1922** [comment]
for me swagger is running but I still encounter the same issue.

**Comment by rukter** [comment]
> @apanicker-nflx please note that the issue was resolved only partially. docker-compose still "fails", please see the previous comment: [#1725 (comment)](https://github.com/Netflix/conductor/issues/1725#issuecomment-641004069)
> 
> Swagger not running on http://localhost:8080/
> 
> http://localhost:5000/ -> Workflow Defs throws an error:
> <img alt="Screenshot_2020-06-30_at_20_50_28" width="1440" src="https://user-images.githubusercontent.com/31187902/86134247-96620380-bb13-11ea-9198-d83fc749bcab.png">

Hi @IanSietro Can you share step for fix this issue ?
