### ISSUE TITLE
Build issues - gradlew build - SubWorkflowParamsTest fails, docker build cant find ./gradlew

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1814]
Having multiple issues with building master branch of Conductor using Windows 10/Gitbash. Just did a clone of the master branch. From the conductor root did a ./gradlew build and it failed on the SubWorkflowParamsTest:

```
com.netflix.conductor.common.workflow.SubWorkflowParamsTest > testWorkflowDefJson FAILED
    org.junit.ComparisonFailure at SubWorkflowParamsTest.java:119

```
Then I tried to do a docker build from the docker directory with 'docker build -t conductor:server ./server' and got this:
```
 ---> b2b927953ec5
Step 5/16 : RUN ./gradlew build -x test
 ---> Running in c49714c655e0
/bin/sh: 1: ./gradlew: not found
The command '/bin/sh -c ./gradlew build -x test' returned a non-zero code: 127
```

Gist link for the full log: https://gist.github.com/rickfish/fc0961a7fb681a7b5455987f934536eb

**Comment by elisherer** [comment]
Docker errors on Windows sometimes relates to having \r\n line endings instead of \n.
If you can, try re-checking-out conductor with unix line endings git configuration and try again.

**Comment by rickfish** [comment]
Thanks @elisherer Not sure why nobody else is running into this as it is a fresh clone of the master branch...

I tried the following but it didn't change anything. 

```
git config --global core.autocrlf input
git config --global core.eol=lf
clone the repo 
./gradlew build

```
I still get the test error and the docker build has the same issue.

**Comment by slipmp** [comment]
I am having the same issue... again!

[image](https://user-images.githubusercontent.com/2482926/89877204-9c1c2180-db74-11ea-930b-e43a025f1ca0.png)

For reference, previously faced and issues were raised on:
https://github.com/Netflix/conductor/issues/1707
https://github.com/Netflix/conductor/issues/1685

**Comment by slipmp** [comment]
Indeed what @elisherer has mentioned made sense.
My PC: Windows 10
Cloning via GitBash.

By executing this line via GitBash:
git config --global core.autocrlf false

Then trying to run docker-compose up on docker folder it passed the line of the error. Essentially the end of line caused a problem. We can easily visualize the difference on Notepad++ via View->Show Symbol->Show End Of Line
![image](https://user-images.githubusercontent.com/2482926/90109279-6f951080-dd00-11ea-93b4-4e4b0656a3e0.png)

Where:
Unix = LF
Macintosh = CR
Windows = CR LF

Eventually docker-compose up works:
![image](https://user-images.githubusercontent.com/2482926/90109538-d31f3e00-dd00-11ea-9065-9cb2152fc480.png)

References:
https://stackoverflow.com/questions/29045140/env-bash-r-no-such-file-or-directory
https://stackoverflow.com/questions/32255747/on-windows-how-would-i-detect-the-line-ending-of-a-file

I think this issue can be closed, thank you!

**Comment by rickfish** [comment]
Not sure what I am doing differently but I tried this with both core.autocrlf true and false. I verified with Notepad++ in both cases that Dockerfile had LF in one case and CRLF in the other case. In both cases I had the same problems discussed in this Issue.

**Comment by slipmp** [comment]
Let me disclose steps I've executed, which is explained on my first reference.

1. Delete your current conductor folder
2. Run git config --global core.autocrlf false; or simply make sure it is already set if you ran in the past
3. Clone conductor repo again
3. Check if end of lines shows as CRLF via NotePad++ by opening a DockerFile, e.g. => conductor/docker/server/DockerFile
4. Run docker-compose up on conductor/docker

You didn't make clear if Repo was cloned again, although you mentioned you saw CRLF... Well I hope that is the difference, otherwise I won't know what is happening on your case @rickfish .

**Comment by rickfish** [comment]
I ran exactly those steps (again) but I had to use core.autocrlf true to get CRLF line endings. I added --config core.autocrlf=true on the git clone command to ensure that it took. Not sure why your autocrlf as false gets CRLF line endings but my setting needs to be true, maybe that is pointing to the issue somehow.

I am cloning fresh every time from the master branch.

Again, I am on Windows 10 Home release 2004 and using git version 2.26.2.windows.1 with the latest Windows Docker Desktop.

**Comment by elisherer** [comment]
@rickfish, if it wasn't clear, docker requires \n (LF) only. It detects the \r (CR) as a character and that's why the bash command fails.
so you need the `core.autocrlf=false` and if possible use `core.eol=lf`.
I also suspect that because the container is running linux, all the other files like config and even Java might suffer from this, and that's why it is best to clone the repo again.
If that doesn't work, there's dos2unix, but that will take some time to run over the whole source.

**Comment by rickfish** [comment]
@elisherer that did the trick - it was a combination of core.autocrlf=false (to get LF) and core.eol=lf. Thanks so much for your help. @slipmp thanks for sticking with me.

**Comment by rickfish** [comment]
closing issue

**Comment by slipmp** [comment]
Nice, it seems I've inverted screenshots then. I am glad this is solved for you @rickfish

**Comment by Raman077** [comment]
`com.netflix.conductor.common.workflow.SubWorkflowParamsTest > testWorkflowDefJson FAILED
    org.junit.ComparisonFailure at SubWorkflowParamsTest.java:119`

Has anyone resolved this issue?

**Comment by mohamedelbalshy** [comment]
> Let me disclose steps I've executed, which is explained on my first reference.
> 
> 1. Delete your current conductor folder
> 2. Run git config --global core.autocrlf false; or simply make sure it is already set if you ran in the past
> 3. Clone conductor repo again
> 4. Check if end of lines shows as CRLF via NotePad++ by opening a DockerFile, e.g. => conductor/docker/server/DockerFile
> 5. Run docker-compose up on conductor/docker
> 
> You didn't make clear if Repo was cloned again, although you mentioned you saw CRLF... Well I hope that is the difference, otherwise I won't know what is happening on your case @rickfish .

thanks this solved my isssue also

**Comment by jegadjame** [comment]
I am getting the same issue again.. I executed git config --global core.autocrlf false and cloned again and ran docker-compose up.. Still getting same error . I am using windows 10 machine

Step 5/15 : RUN ./gradlew build -x test --stacktrace
 ---> Running in 05a800bde887
Downloading https://services.gradle.org/distributions/gradle-7.5.1-bin.zip

Exception in thread "main" java.io.IOException: Downloading from https://services.gradle.org/distributions/gradle-7.5.1-bin.zip failed: timeout
        at org.gradle.wrapper.Download.downloadInternal(Download.java:122)
        at org.gradle.wrapper.Download.download(Download.java:80)
        at org.gradle.wrapper.Install$1.call(Install.java:83)
        at org.gradle.wrapper.Install$1.call(Install.java:63)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:63)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:305)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:507)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:602)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:207)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:193)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:100)
        ... 7 more
The command '/bin/sh -c ./gradlew build -x test --stacktrace' returned a non-zero code: 1
Service 'conductor-server' failed to build : Build failed

Thanks in advance,
Jegadeesh

**Comment by manan164** [comment]
Hi @jegadjame ,
Please follow the steps,
1. Delete your current conductor folder
2. Run **git config --global core.autocrlf false**; 
3. Run **git config --global core.eol lf**; (Small L and f)
4. Clone conductor repo again
5. Check if end of lines shows as CRLF via NotePad++ by opening a DockerFile, e.g. => conductor/docker/server/DockerFile
6. Run docker-compose up on conductor/docker
